### ISSUE TITLE
How can I have the individual level data in your program?

### ISSUE THREAD

**Issue by ldmpku** [AnttiVainio/Steam-crawler#1]

**Comment by AnttiVainio** [comment]
If you are running the crawler successfully, it saves all the crawled data into mem/data. You can open that file in some text editor, and when you see this kind of lines:
0:1:0:1:1614:79:267:3242:25:1:1:12:0:8:0:0:103:79:53
the level is the 6th number which is 79 in this case.

**Comment by ldmpku** [comment]
Sorry for misunderstanding. I mean the individual-level data which is the
games they have, how long they have played and etc.

Also, can you give me a more specific instruction on the sever setup? I
just want those original data instead of those summaries of data stored in
my own computer.

Can I set up the server in my own computer?


2017-10-20 12:20 GMT-04:00 Antti Vainio <notifications@github.com>:

**Comment by AnttiVainio** [comment]
You can get some of that data but not all of it. If you have a look at my website, you can basically get anything that is visible there but nothing else when using this crawler. That means you can get the amount of games they have but not the playtime for instance.

Anyway, if you really want to run this crawler yourself, you don't even need any server at all because that is optional. All the data the crawler generates is available also locally. I never really intended other people to run the crawler but rather for learning purposes, so I put in a couple things to slow people down. Rather simple stuff really but let that be a little exercise just to see that you have at least some idea on what you are doing. Just run main.py to see for yourself. It's also a good idea to take a glimpse at settings.py.

Once you have the data, it should be quite simple to figure out what each number means. Just check the profile that was crawler and compare the numbers. There's also good stuff at the beginning of crawl.py.

If you instead just want to crawl just a few people, like 1 or 2 or maybe 10 specific guys, it would be much simpler to just create a simple Python program yourself. Running this program is overkill for that and you can't control who is crawled anyway. You can have a look at request.py to see how I load web pages.

**Comment by ldmpku** [comment]
Thank u. Really appreciate it.

I do have my crawling script just not as good as yours.
